### ISSUE TITLE
Multi-step handlers

### ISSUE THREAD

**Issue by dboitnot** [sigdba/clj-beq#11]
It would be handy to provide post-processing handlers which could take the results of the runner execution and perform some simple action(s) such as:

- Push a message into a DBMS_PIPE
- Fire a DBMS_ALERT
- Perform some DML statement
- Append to a log file

To support this a templating system such as [Selmer](https://github.com/yogthos/Selmer) could be available to the user providing access to data returned by the runner. Each runner should have it's own key within the top-level map passed to the template engine.

A great way to deal with this would be to provide multi-step handlers. So instead of this:

```
  - event-code: SOME_EVENT
    type: twilio
    to-number-parm: TO
    body-parm: BODY
```

We'd do something like:
```
  - event-code: SOME_EVENT
    steps:
      - type: twilio
        to-number-parm: TO
        body-parm: BODY
```
