### ISSUE TITLE
Time of Day handling

### ISSUE THREAD

**Issue by atravis** [sigdba/clj-beq#12]
Consider adding time of day handling to the processor.  When running as a system process, we don't have any easy way to start and stop the event processor, like we do when running from a job scheduler.  Consider adding parameters to the YML configuration (either overall or by process) for daily start time and daily stop time.  If current time not between start time and stop time just go to the sleep step.

There are many ways to make this more advanced, but just having this basic step would help provide a layer of protection for the whole process.

**Comment by dboitnot** [comment]
Propose adding an optional `defer-during` key to event handlers which could be used to specify a "blackout period" when events will not be processed. The value would be specified as a range between two ISO-8601 times separated by a hyphen.

Example:
```yaml
event-handlers:
  - event-code: SMS_SEND
    defer-during: "20:00 - 08:00"
    steps:
      - type: twilio
```

Timezones would be specified as ISO-8601 offsets (e.g. `10:15:30+01:00`) and handled in this way:
1. If both times have offsets they will apply to their individual times.
2. If one time has an offset and the other doesn't then the offset will apply to both.
3. If neither has an offset then the system timezone will be used.

**Comment by atravis** [comment]
I like the simplicity of the single parameter and ability to set a timezone.  This looks like a good way to address the feature request.

**Comment by dboitnot** [comment]
After digging in documentation and playing with some test code, I'm finding two problems with the above approach:
1. The hyphen complicates parsing because it's also a valid character in ISO-8601 time offsets.
2. ISO-8601 offsets do not take daylight savings times into account.

How do we feel about this approach:
```yaml
event-handlers:
  - event-code: SMS_SEND 
    schedule:
      not-before: "08:00"
      not-after: "20:00"
      timezone: US/Eastern
    steps:
      - type: twilio
```

This is a little more verbose but it leaves room for additional options in future and support for actual timezones which account for DST.
